// Copyright 2021 Volkan Yazıcı <volkan@yazi.ci>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

https://github.com/vy/date-time-format-benchmark/actions[image:https://github.com/vy/date-time-format-benchmark/workflows/build/badge.svg[CI Status]]
https://www.apache.org/licenses/LICENSE-2.0.txt[image:https://img.shields.io/github/license/vy/date-time-format-benchmark.svg[License]]

Benchmarking project comparing various Java date & time formatter performances.

== Usage

Even though all the benchmarked formatters are compatible with Java 8, Java 17 or higher is required for the purpose of running on a modern Java stack.

. Build sources:
+
[source,bash]
----
./mvnw clean package
----

. Run benchmarks:
+
[source,bash]
----
java -jar target/date-time-format-benchmark.jar -f 0 -wi 0 -i 1 -r 10s
----

For samples, see https://github.com/vy/date-time-format-benchmark/actions[earlier runs performed by CI].
